// Canonical codes and exact English picker labels observed in Studio on 2026-10-07.
const entries = [
  ['af', 'Afrikaans'],
  ['sq', 'Albanian'],
  ['am', 'Amharic'],
  ['ar', 'Arabic'],
  ['hy', 'Armenian'],
  ['az', 'Azerbaijani'],
  ['bn', 'Bangla'],
  ['bn-IN', 'Bangla (India)'],
  ['eu', 'Basque'],
  ['be', 'Belarusian'],
  ['bs', 'Bosnian'],
  ['bg', 'Bulgarian'],
  ['my', 'Burmese'],
  ['yue', 'Cantonese'],
  ['yue-HK', 'Cantonese (Hong Kong)'],
  ['ca', 'Catalan'],
  ['zh', 'Chinese'],
  ['zh-CN', 'Chinese (China)'],
  ['zh-HK', 'Chinese (Hong Kong)'],
  ['zh-Hans', 'Chinese (Simplified)'],
  ['zh-SG', 'Chinese (Singapore)'],
  ['zh-TW', 'Chinese (Taiwan)'],
  ['zh-Hant', 'Chinese (Traditional)'],
  ['hr', 'Croatian'],
  ['cs', 'Czech'],
  ['da', 'Danish'],
  ['nl', 'Dutch'],
  ['nl-BE', 'Dutch (Belgium)'],
  ['nl-NL', 'Dutch (Netherlands)'],
  ['en', 'English'],
  ['en-AU', 'English (Australia)'],
  ['en-CA', 'English (Canada)'],
  ['en-IN', 'English (India)'],
  ['en-IE', 'English (Ireland)'],
  ['en-GB', 'English (United Kingdom)'],
  ['en-US', 'English (United States)'],
  ['et', 'Estonian'],
  ['fil', 'Filipino'],
  ['fi', 'Finnish'],
  ['fr', 'French'],
  ['fr-BE', 'French (Belgium)'],
  ['fr-CA', 'French (Canada)'],
  ['fr-FR', 'French (France)'],
  ['fr-CH', 'French (Switzerland)'],
  ['gl', 'Galician'],
  ['ka', 'Georgian'],
  ['de', 'German'],
  ['de-AT', 'German (Austria)'],
  ['de-DE', 'German (Germany)'],
  ['de-CH', 'German (Switzerland)'],
  ['el', 'Greek'],
  ['gu', 'Gujarati'],
  ['ht', 'Haitian Creole'],
  ['he', 'Hebrew'],
  ['hi', 'Hindi'],
  ['hu', 'Hungarian'],
  ['is', 'Icelandic'],
  ['ig', 'Igbo'],
  ['id', 'Indonesian'],
  ['ga', 'Irish'],
  ['it', 'Italian'],
  ['ja', 'Japanese'],
  ['jv', 'Javanese'],
  ['kn', 'Kannada'],
  ['kk', 'Kazakh'],
  ['km', 'Khmer'],
  ['rw', 'Kinyarwanda'],
  ['ko', 'Korean'],
  ['ku', 'Kurdish'],
  ['ky', 'Kyrgyz'],
  ['lo', 'Lao'],
  ['la', 'Latin'],
  ['lv', 'Latvian'],
  ['lt', 'Lithuanian'],
  ['mk', 'Macedonian'],
  ['mg', 'Malagasy'],
  ['ms', 'Malay'],
  ['ms-SG', 'Malay (Singapore)'],
  ['ml', 'Malayalam'],
  ['mt', 'Maltese'],
  ['mi', 'Māori'],
  ['mr', 'Marathi'],
  ['mn', 'Mongolian'],
  ['ne', 'Nepali'],
  ['no', 'Norwegian'],
  ['or', 'Odia'],
  ['ps', 'Pashto'],
  ['fa', 'Persian'],
  ['fa-AF', 'Persian (Afghanistan)'],
  ['fa-IR', 'Persian (Iran)'],
  ['pl', 'Polish'],
  ['pt', 'Portuguese'],
  ['pt-BR', 'Portuguese (Brazil)'],
  ['pt-PT', 'Portuguese (Portugal)'],
  ['pa', 'Punjabi'],
  ['ro', 'Romanian'],
  ['ro-MD', 'Romanian (Moldova)'],
  ['ru', 'Russian'],
  ['sr', 'Serbian'],
  ['sr-Cyrl', 'Serbian (Cyrillic)'],
  ['sr-Latn', 'Serbian (Latin)'],
  ['si', 'Sinhala'],
  ['sk', 'Slovak'],
  ['sl', 'Slovenian'],
  ['so', 'Somali'],
  ['es', 'Spanish'],
  ['es-419', 'Spanish (Latin America)'],
  ['es-MX', 'Spanish (Mexico)'],
  ['es-ES', 'Spanish (Spain)'],
  ['es-US', 'Spanish (United States)'],
  ['sw', 'Swahili'],
  ['sv', 'Swedish'],
  ['ta', 'Tamil'],
  ['te', 'Telugu'],
  ['th', 'Thai'],
  ['tr', 'Turkish'],
  ['uk', 'Ukrainian'],
  ['ur', 'Urdu'],
  ['uz', 'Uzbek'],
  ['vi', 'Vietnamese'],
  ['cy', 'Welsh'],
  ['xh', 'Xhosa'],
  ['yi', 'Yiddish'],
  ['yo', 'Yoruba'],
  ['zu', 'Zulu'],
] as const;
export const languages = entries.map(([code, name]) => ({
  code,
  name,
  studioCode: code === 'he' ? 'iw' : code,
}));
export const languageName = (code: string) =>
  languages.find((x) => x.code === code)?.name ?? code;
export const canonicalCode = (code: string) => (code === 'iw' ? 'he' : code);
export const studioCode = (code: string) =>
  languages.find((x) => x.code === code)?.studioCode ?? code;
export const codeFromName = (name: string) =>
  languages.find((x) => x.name === name.trim())?.code;
